config/routes.rb
Rails.application.routes.draw do

  root to: "cocktails#index"

  resources :cocktails do
    resources :doses, only: [:new, :create] 
  end
  resources :doses, only: [:destroy], as: "dose"  
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cocktail.rb
class Cocktail < ApplicationRecord
  has_many :doses, dependent: :destroy
  has_many :ingredients, through: :doses
  
  has_one_attached :photo
  # if multiple photos use :photos

  validates :name, presence: true, uniqueness: true, allow_blank: false
end

app/models/dose.rb
class Dose < ApplicationRecord
  belongs_to :cocktail
  belongs_to :ingredient

  validates :description, presence: true, allow_blank: false

  validates :cocktail_id, uniqueness: { scope: :ingredient_id }

  # validates :cocktail_id, uniqueness: true
  # validates :ingredient_id, uniqueness: true

end

app/models/ingredient.rb
class Ingredient < ApplicationRecord
  has_many :doses

  validates :name, presence: true, uniqueness: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/cocktails_controller.rb
class CocktailsController < ApplicationController
  before_action :set_cocktail, only: [:show, :edit, :update, :destroy]

  def index
    @cocktails = Cocktail.all
  end

  def show
  end

  def new
    @cocktail = Cocktail.new
  end

  def create
    @cocktail = Cocktail.new(cocktail_params)

    if @cocktail.save
      redirect_to cocktail_path(@cocktail)
    else
      render :new
    end
  end

  def edit
  end

  def update
    @cocktail.update(cocktail_params)

    if @cocktail.save
      redirect_to cocktails_path
    else
      render :new
    end
  end

  def destroy
    @cocktail.destroy
    redirect_to new_cocktail_path
  end

  private

  def set_cocktail
    @cocktail = Cocktail.find(params[:id])
  end

  def cocktail_params
    params.require(:cocktail).permit(:name, :photo)   
  end

end

app/controllers/doses_controller.rb
class DosesController < ApplicationController

  def new
    @dose = Dose.new
    @cocktail = Cocktail.find(params[:cocktail_id])
  end

  def create
    @dose = Dose.new(dose_params)
    @cocktail = Cocktail.find(params[:cocktail_id])
    @dose.cocktail = @cocktail

    if @dose.save
      redirect_to cocktail_path(@cocktail)
    else
      render :new
    end
  end

  def destroy
    @dose = Dose.find(params[:id])
    # @cocktail = Cocktail.find(params[:cocktail_id])
    # @dose.cocktail = @cocktail
    
    @dose.destroy

    redirect_to cocktails_path
  end

  private

  def dose_params
    params.require(:dose).permit(:description, :ingredient_id)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cocktails_helper.rb
module CocktailsHelper
end

app/helpers/doses_helper.rb
module DosesHelper
end

app/views/cocktails/edit.html.erb
<%= simple_form_for @cocktail do |element| %>
  <%= element.input :name %>
  <%= element.submit %>
<% end %>

<%= link_to "Return", "/cocktails/#{@cocktail.id}" %>

app/views/cocktails/index.html.erb
<div class="container d-flex">
  <div class="row">    
    <% @cocktails.each do |element| %>
      <div class="col-4">
          <div class="card  m-3" style="width: 18rem;">

            <% if element.photo.attached? %>
            <%=  cl_image_tag element.photo.key, class: "card-img-top" %>
            <% else %>
            <% puts "NO IMAGE" %>
            <% end %>

            <div class="card-body">
              <h5 class="card-title"><%= element.name  %></h5>
              <%= link_to "Check out #{element.name}", "/cocktails/#{element.id}", class: "btn btn-secondary btn-lg" %>
            </div>
          </div>
      </div>
    <% end %>
  </div>
</div>

app/views/cocktails/new.html.erb
<%= simple_form_for @cocktail do |f| %>
  <%= f.input :name %>
  <%= f.input :photo, as: :file %>
  <%# if multiple phots will be uploaded change :photo to :photos, and add input_html { multiple: true } %>
  <%= f.submit class: "btn btn-primary" %>
<% end %>

<%= link_to "Return", "/cocktails" %>

app/views/cocktails/show.html.erb
<h1>
    <%= @cocktail.name %>
</h1>
<br>
<ul>
  <% @cocktail.doses.each do |dose| %>
  <li> What it takes?
  <br>
  <%= dose.description %>
  of
  <%= dose.ingredient.name %>
  <br>
  <%= link_to "Delete Dose", dose_path(dose), method: :delete, data: { confirm: "Are you sure?" } %>
  </li>
  <% end %>
</ul>

<%= link_to "Edit Cocktail", edit_cocktail_path%>
<br>
<%= link_to "Edit Doses", new_cocktail_dose_path(@cocktail)%>
<br>
<%= link_to "Delete Cocktail #{@cocktail.name}", cocktail_path(@cocktail), method: :delete, data: {confirm: "Are you sure?"}%>
<br>
<%= link_to "Return", cocktails_path %>

app/views/doses/new.html.erb
<h1>Add doses to your <%= @cocktail.name %></h1>

<%= simple_form_for [@cocktail, @dose] do |f| %>
  <%= f.input :description %>
  <%= f.association :ingredient %>
    <%= f.submit class: "btn btn-primary" %>
<% end %>


<%= link_to "Return", "/cocktails" %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
    <link href="https://fonts.googleapis.com/css2?family=MedievalSharp&display=swap" rel="stylesheet">
    <title>RailsMisterCocktail</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'shared/navbar' %>
    <%= yield %>
  </body>
</html>

app/views/shared/_navbar.html.erb
<div class="d-flex  navbar navbar-expand-sm navbar-light navbar-lewagon ">
  <%= link_to "#", class: "navbar-brand" do %>
    <%= image_tag "https://image.flaticon.com/icons/svg/1355/1355838.svg" %>
    <% end %>

  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <h1>CROM DRINKS</h1>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item">
        <%= link_to "Make new offering", new_cocktail_path, class: "nav-link" %>
      </li>
      <li class="nav-item">
        <%= link_to "Home", cocktails_path, class: "nav-link" %>
      </li>
      <li class="nav-item dropdown">
        <%= image_tag "https://i.guim.co.uk/img/media/2931bcb9103e93e79f99ec0327c318efc6b5b3f6/0_154_2968_1781/master/2968.jpg?width=1200&height=1200&quality=85&auto=format&fit=crop&s=d7fa021569af63af16986f7363034a0b", class: "avatar dropdown-toggle", id: "navbarDropdown", data: { toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>
        <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
          <%= link_to "About", "#", class: "dropdown-item" %>
          <%= link_to "Contact Us", "#", class: "dropdown-item" %>
        </div>
      </li>
    </ul>
  </div>
</div>